### ISSUE TITLE
Aggregation objects

### ISSUE THREAD

**Issue by mindrones** [nestauk/dapsboard#183]
Collect aggregation info into objects where we can collect props like:
- field type
- docs
- doc path (assuming a common base URL)
- availability: array of ES versions (`from`, `to` optional)
- params
- id
- label
- params doc

This will help having all props in a single place and write more functional code, avoiding functions requiring imported globals.

**Comment by mindrones** [comment]
Here are the current associations `aggregationId` to `fieldType`, named tentatively. Some group seem to overlap or be the same, so I'll probably merge them.

```yaml
allButText:
  aggs:
    - cardinality
    - diversified_sampler
    - missing
    - nested
    - reverse_nested
    - sampler
    - value_count
  types:
    - boolean
    - date
    - Date_YYYYMMDD_dash
    - Date_YYYYMMDD_dash_time
    - ES_geo_point_obj
    - ES_keyword
    - ES_keyword[]
    - ES_text_w_keyword
    - ES_text_w_keyword[]
    - float
    - integer
numerical:
  aggs:
    - extended_stats
  types:
    - boolean
    - date
    - Date_YYYYMMDD_dash
    - Date_YYYYMMDD_dash_time
    - float
    - integer
numerical:
  aggs:
    - avg
    - max
    - median_absolute_deviation
    - min
    - percentiles
    - stats
    - sum
    - weighted_avg
  types:
    - date
    - Date_YYYYMMDD_dash
    - Date_YYYYMMDD_dash_time
    - float
    - integer
dates:
  aggs:
    - auto_date_histogram
    - date_histogram
    - date_range
  types:
    - date
    - Date_YYYYMMDD_dash
    - Date_YYYYMMDD_dash_time,
numerical:
  aggs:
    - percentile_ranks
  types:
    - date
    - Date_YYYYMMDD_dash_time
    - float
    - integer

# I'd remove the association terms -> dates and numbers
esSearchableString:
  aggs:
    - terms
  types:
    # - date
    # - Date_YYYYMMDD_dash
    # - Date_YYYYMMDD_dash_time
    - ES_keyword
    - ES_keyword[]
    - ES_text_w_keyword
    - ES_text_w_keyword[]
    # - float
    # - integer
geoPointObject:
  aggs:
    - geo_bounds
    - geo_centroid
    - geo_distance
    - geohash_grid
  types:
    - ES_geo_point_obj
esSearchableString:
  aggs:
    - rare_terms
    - significant_terms
  types:
    - ES_keyword
    - ES_keyword[]
    - ES_text_w_keyword
    - ES_text_w_keyword[]
esStrings:
  aggs:
    - significant_text
  types:
    - ES_keyword
    - ES_keyword[]
    - ES_text
    - ES_text[]
    - ES_text_w_keyword
    - ES_text_w_keyword[]
number:
  aggs:
    - histogram
  types:
    - float
    - integer
```
